[[libsass]]
arch = "aarch64"
git-tree-sha1 = "1c67bf11df76b57bc4f90d0dbcdb7f054b48e4b9"
os = "macos"

    [[libsass.download]]
    sha256 = "1b0d3872c1ffab36e45f72ddebf31dd2cf29b9175590927ede9871222ad88948"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.aarch64-apple-darwin.tar.gz"
[[libsass]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "95cf0082b9f1984b6569c2ea9c6e6835ffcebc3b"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "9d0bf9bee96360e926eb310720be4a2287fe6d6ef2213c60e89932642390a7c1"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.aarch64-linux-gnu-cxx03.tar.gz"
[[libsass]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f0e2a81420f82697e63bf5a9b12d7b80b1bf55c"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "ad15b65a36467a8e0b3f815d513ba992aaaf4fa78f5ac18524d50f2fb6887a17"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.aarch64-linux-gnu-cxx11.tar.gz"
[[libsass]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3c3025893fc45606137e2004abed4ce0c18e3134"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "1f85f3ef10dd16892c718bed3b3c6f880d6a1665b403070ff5719daf6bcda895"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.aarch64-linux-musl-cxx03.tar.gz"
[[libsass]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "166bf7b1c356df2258bef6125d86187e9089a839"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "35e280e9dfed3920bc7340b3a4dbe9914014648ab0cb1b77679c026ff84cc5b9"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.aarch64-linux-musl-cxx11.tar.gz"
[[libsass]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9c33b96f65cff0c02cce318a237538033396e72b"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "1a66deea35b7f6b0687c7eafdc7315e1a787e305c30afb6d90f92a859dcbb332"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[libsass]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fd1ed8da1dc98e63465ed469bef08edfbde955b7"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "4e148e81875152270d6e68553ef5c5b6b3904b18bf246f0b103696c2872b87d1"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[libsass]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "3523bdff8874d20897237c376df0dcd453a8b5cb"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "91cb2f27c0e9e1775840988915345a642220e98e70b1a3cea65f23cba999968e"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.armv6l-linux-musleabihf-cxx03.tar.gz"
[[libsass]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db24c82dbac93319b60aec1ca3b8509a322013bb"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "ff4ee812e2ef265cf2f86c3395298de37d62b76de3fb652c89422054fc637918"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.armv6l-linux-musleabihf-cxx11.tar.gz"
[[libsass]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "89ffcf951bde0760a265595a5056ba66d372cc4f"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "b71d91f1eceadf691b5d61f2153cfef571fb29671e9f4c8e5f793889850e5955"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[libsass]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3a18ba27b46dffefd812b0fbbee3b0f311b08e53"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "22d0df9a70cac161fb3d859a6df8da0f1220fee2dbd4edea08e6a7dc6d1d632f"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[libsass]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20584849cbaa9d787b47c04d9124a2cb61791a55"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "07c8044c758d0892c83eefd915731ff17e1417bc39823546c47fdc95e95c0537"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.armv7l-linux-musleabihf-cxx03.tar.gz"
[[libsass]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8138046fc0a98613e35d030c56f8d0726386d1e8"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "a981c9796c2e1f840523687a75839660bf5f7ab5d35db6e8f8f8a073b15d48f4"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.armv7l-linux-musleabihf-cxx11.tar.gz"
[[libsass]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "43d6f4c083de8c312ced7807bef7a0b90aeef5f8"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "237013e394a3582f81ff729069d4ffae13874be2747d5c025b98909a37da6a58"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.i686-linux-gnu-cxx03.tar.gz"
[[libsass]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d2144ef283d07d65921d68471631fe6941ad3b94"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "8de1f9c7695a6cd7d401c31a4ff5c8b099c70853eacf6f4e68ba8e69e2664c7a"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.i686-linux-gnu-cxx11.tar.gz"
[[libsass]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "21cddba803aae5f42f84e5414d193b23414c28ec"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "53cfe69b5a17f5f7b096b35c2c856833be894c19ed3399760b4e1e0a56385723"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.i686-linux-musl-cxx03.tar.gz"
[[libsass]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "91bd152c7f0ec5e112f12e3e17af433ea99f1740"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "959782ab376c0160c2d28c79b94abea465f76f87342c5890fd55c23404b099a8"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.i686-linux-musl-cxx11.tar.gz"
[[libsass]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72e74d33276cbffedeeee98a9e397f87ccf984b9"
os = "windows"

    [[libsass.download]]
    sha256 = "d48f87eaf2c99305fc83a826b48bfd3e9e79b8ac4551785b200fd75fd9b34d9c"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.i686-w64-mingw32-cxx03.tar.gz"
[[libsass]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "42fe50d0f4b21b941b8cbe1f8e18ce3c91a4dd4a"
os = "windows"

    [[libsass.download]]
    sha256 = "a5ee590c2e32b9fbe201942859bd1f5f13f618521a34e182f328a05ef7ffed82"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.i686-w64-mingw32-cxx11.tar.gz"
[[libsass]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "65817457cd9d5ab9b88c8e607d5bb109bb6df4b5"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "de960d389cc32fc2166f119a6e59eef806c771c270daad8166bb60c005c832f0"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.powerpc64le-linux-gnu-cxx03.tar.gz"
[[libsass]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e8f5b5ea9a9f0bd81e1c81f25188b177eb93fed6"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "7d55b0586b6fb90c5ec17c8fcc07800b5514894fb7ecb4b392a3c697f11f7f17"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.powerpc64le-linux-gnu-cxx11.tar.gz"
[[libsass]]
arch = "x86_64"
git-tree-sha1 = "5d080b5226a253e9b099f41c4705cdbf1dacb347"
os = "macos"

    [[libsass.download]]
    sha256 = "5ea4cd78acc6eb6c0189f056e445b0fc2e951eda56d3e9e02dc538401f03e839"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.x86_64-apple-darwin.tar.gz"
[[libsass]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9ddfc4c1839d5996ec593960f6922783606eb80b"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "9ee1096dad1cef0b4578db0b1b8d49235ac687fc5311f6b92b4e1e5d07dd6bbd"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.x86_64-linux-gnu-cxx03.tar.gz"
[[libsass]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f800738add5637023bc0369e81c04015aa95889a"
libc = "glibc"
os = "linux"

    [[libsass.download]]
    sha256 = "8aaf45b459db754d3aa04e723b45fa598e26be27fc2655e11b5ecb3968e46da8"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.x86_64-linux-gnu-cxx11.tar.gz"
[[libsass]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2a9edc5ce09d63c323677ad09e8504b6e836b52b"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "ef50f6966584ddf8a9d09246094f0aefa9ff9907c753c9aedb4cfec85aa15403"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.x86_64-linux-musl-cxx03.tar.gz"
[[libsass]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "60da6e989f23db4e20257244431aaa0b669166e8"
libc = "musl"
os = "linux"

    [[libsass.download]]
    sha256 = "a034124dda539173edf279db9eb78cf33c3015ef81370b93a93d83f725c76111"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.x86_64-linux-musl-cxx11.tar.gz"
[[libsass]]
arch = "x86_64"
git-tree-sha1 = "b481bcf0b8199030d27286277c480b3a24566dc5"
os = "freebsd"

    [[libsass.download]]
    sha256 = "74780189deee5936074477a174445fc6539e54f61ef50b7091454e7bab03d0ce"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.x86_64-unknown-freebsd.tar.gz"
[[libsass]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bdf2aef1e15799b41f7631ecda3f17e97112cb89"
os = "windows"

    [[libsass.download]]
    sha256 = "81333b6712dd80222bfbfec574417c95575b0707a618b4794407e6617aeff11a"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.x86_64-w64-mingw32-cxx03.tar.gz"
[[libsass]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b14924176cc6a9eaab5d573c7b726c0c4d57182e"
os = "windows"

    [[libsass.download]]
    sha256 = "20ee49733a99a27ccefcb5b8a9fd4cbf19cbdc9dcc817e984263a286544a16d7"
    url = "https://github.com/JuliaBinaryWrappers/libsass_jll.jl/releases/download/libsass-v3.6.4+0/libsass.v3.6.4.x86_64-w64-mingw32-cxx11.tar.gz"
